### ISSUE TITLE
Add flag to allow avoiding calling dibs on environments that haven't completed spin up

### ISSUE THREAD

**Issue by jessetab** [tableau-mkt/dibs#2]
Haven't looked too deeply into it, just noticing a string of build errors on Travis following a shiproom session in which Travis seems to be attempting to updb on an environment that may not be 100% ready yet?

![tinygrab screen shot 11-1-16 4 34 01 pm](https://cloud.githubusercontent.com/assets/14878536/19911655/19c8dc2a-a052-11e6-99e5-8e5868ce8fab.png)
![tinygrab screen shot 11-1-16 4 42 46 pm](https://cloud.githubusercontent.com/assets/14878536/19911688/4bf440e0-a052-11e6-8899-fa4d51955cd6.png)
<img width="1047" alt="tinygrab screen shot 11-1-16 3 23 32 pm" src="https://cloud.githubusercontent.com/assets/14878536/19911670/26e31dbc-a052-11e6-9811-d46ce24cf8cc.png">

**Comment by jessetab** [comment]
Tested it out by starting an environment spin up process, then calling dibs on it before the multidev creation could be completed. 

```JECHEN-MAC3:~ jechen$terminus site create-env --site=tableau --from-env=test --to-env=test-dibs
JECHEN-MAC3:~ jechen$ terminus site dibs --site=tableau --env=test-dibs
Called dibs on: test-dibs```

However, not sure if the issue should be addressed here... calling dibs on an environment that is in the process of being created could be useful in some scenarios. Maybe the Travis build script would be a more appropriate location to check if an environment is ready yet.

**Comment by iamEAP** [comment]
Yeah, this is real.  Maybe we add a flag for "only try to dibs completely spun-up environments."

**Comment by iamEAP** [comment]
Might also just go the direction where:
- If you dibs a specific environment, you obviously know what you're doing, and we'll let you do that, even if the site's still spinning up. (Use-case: you're a real person and you want to make sure no one else grabs your multidev)
- If you dibs with no specific environment, we'll only limit the list to just those that are functional.

Easiest way I can see to approximate this is to check the MySQL information schema for a key table that's relatively far down the list alphabetically (like a user table).  `users` for Drupal and `wp_users` for WordPress.
